// export const natCont = [
//     { nationality: "Afghan", continent: "Asie" },
//     { nationality: "Sud-Africain", continent: "Afrique" },
//     { nationality: "Albanais", continent: "Europe" },
//     { nationality: "Algérien", continent: "Afrique" },
//     { nationality: "Allemand", continent: "Europe" },
//     { nationality: "Américain", continent: "Amérique du Nord" },
//     { nationality: "Andorran", continent: "Europe" },
//     { nationality: "Angolais", continent: "Afrique" },
//     { nationality: "Antiguayen", continent: "Amérique" },
//     { nationality: "Saoudien", continent: "Asie" },
//     { nationality: "Argentin", continent: "Amérique du Sud" },
//     { nationality: "Arménien", continent: "Asie/Europe" },
//     { nationality: "Australien", continent: "Australie" },
//     { nationality: "Autrichien", continent: "Europe" },
//     { nationality: "Azerbaïdjanais", continent: "Asie/Europe" },
//     { nationality: "Bahaméen", continent: "Amérique" },
//     { nationality: "Bangladais", continent: "Asie" },
//     { nationality: "Barbadien", continent: "Amérique" },
//     { nationality: "Belge", continent: "Europe" },
//     { nationality: "Béninois", continent: "Afrique" },
//     { nationality: "Bhoutanais", continent: "Asie" },
//     { nationality: "Biélorusse", continent: "Europe" },
//     { nationality: "Birman", continent: "Asie" },
//     { nationality: "Bolivien", continent: "Amérique du Sud" },
//     { nationality: "Bosniaque", continent: "Europe" },
//     { nationality: "Botswanais", continent: "Afrique" },
//     { nationality: "Brésilien", continent: "Amérique du Sud" },
//     { nationality: "Britannique", continent: "Europe" },
//     { nationality: "Brunéien", continent: "Asie" },
//     { nationality: "Bulgare", continent: "Europe" },
//     { nationality: "Burkinabé", continent: "Afrique" },
//     { nationality: "Burundais", continent: "Afrique" },
//     { nationality: "Cambodgien", continent: "Asie" },
//     { nationality: "Camerounais", continent: "Afrique" },
//     { nationality: "Canadien", continent: "Amérique du Nord" },
//     { nationality: "Centrafricain", continent: "Afrique" },
//     { nationality: "Chilien", continent: "Amérique du Sud" },
//     { nationality: "Chinois", continent: "Asie" },
//     { nationality: "Colombien", continent: "Amérique du Sud" },
//     { nationality: "Congolais", continent: "Afrique" },
//     { nationality: "Sud-Coréen", continent: "Asie" },
//     { nationality: "Nord-Coréen", continent: "Asie" },
//     { nationality: "Cubain", continent: "Amérique" },
//     { nationality: "Danois", continent: "Europe" },
//     { nationality: "Djiboutien", continent: "Afrique" },
//     { nationality: "Dominicain", continent: "Amérique" },
//     { nationality: "Égyptien", continent: "Afrique" },
//     { nationality: "Émirati", continent: "Asie" },
//     { nationality: "Espagnol", continent: "Europe" },
//     { nationality: "Estonien", continent: "Europe" },
//     { nationality: "Éthiopien", continent: "Afrique" },
//     { nationality: "Français", continent: "Europe" },
//     { nationality: "Gabonais", continent: "Afrique" },
//     { nationality: "Grec", continent: "Europe" },
//     { nationality: "Guinéen", continent: "Afrique" },
//     { nationality: "Haïtien", continent: "Amérique" },
//     { nationality: "Indien", continent: "Asie" },
//     { nationality: "Indonésien", continent: "Asie" },
//     { nationality: "Irlandais", continent: "Europe" },
//     { nationality: "Israélien", continent: "Asie" },
//     { nationality: "Italien", continent: "Europe" },
//     { nationality: "Japonais", continent: "Asie" },
//     { nationality: "Marocain", continent: "Afrique" },
//     { nationality: "Mexicain", continent: "Amérique du Nord" },
//     { nationality: "Néerlandais", continent: "Europe" },
//     { nationality: "Néo-Zélandais", continent: "Océanie" },
//     { nationality: "Nigérian", continent: "Afrique" },
//     { nationality: "Norvégien", continent: "Europe" },
//     { nationality: "Pakistanais", continent: "Asie" },
//     { nationality: "Palestinien", continent: "Asie" },
//     { nationality: "Péruvien", continent: "Amérique du Sud" },
//     { nationality: "Philippin", continent: "Asie" },
//     { nationality: "Polonais", continent: "Europe" },
//     { nationality: "Portugais", continent: "Europe" },
//     { nationality: "Qatari", continent: "Asie" },
//     { nationality: "Roumain", continent: "Europe" },
//     { nationality: "Russe", continent: "Europe/Asie" },
//     { nationality: "Sénégalais", continent: "Afrique" },
//     { nationality: "Serbe", continent: "Europe" },
//     { nationality: "Suisse", continent: "Europe" },
//     { nationality: "Turc", continent: "Asie/Europe" },
//     { nationality: "Ukrainien", continent: "Europe" },
//     { nationality: "Vietnamien", continent: "Asie" },
//     { nationality: "Zambien", continent: "Afrique" },
//     { nationality: "Zimbabwéen", continent: "Afrique" }
//   ];
  
export const natCont = [
    { nationality: "Afghan", continent: "Asie" },
    { nationality: "Sud-Africain", continent: "Afrique" },
    { nationality: "Albanais", continent: "Europe" },
    { nationality: "Algérien", continent: "Afrique" },
    { nationality: "Allemand", continent: "Europe" },
    { nationality: "Américain", continent: "Amérique du Nord" },
    { nationality: "Andorran", continent: "Europe" },
    { nationality: "Angolais", continent: "Afrique" },
    { nationality: "Antiguais", continent: "Amérique du Nord" },
    { nationality: "Saoudien", continent: "Asie" },
    { nationality: "Argentin", continent: "Amérique du Sud" },
    { nationality: "Arménien", continent: "Asie/Europe" },
    { nationality: "Australien", continent: "Australie" },
    { nationality: "Autrichien", continent: "Europe" },
    { nationality: "Azerbaïdjanais", continent: "Asie/Europe" },
    { nationality: "Bahaméen", continent: "Amérique du Nord" },
    { nationality: "Bangladais", continent: "Asie" },
    { nationality: "Barbadien", continent: "Amérique du Nord" },
    { nationality: "Belge", continent: "Europe" },
    { nationality: "Béninois", continent: "Afrique" },
    { nationality: "Bhoutanais", continent: "Asie" },
    { nationality: "Biélorusse", continent: "Europe" },
    { nationality: "Birman", continent: "Asie" },
    { nationality: "Bolivien", continent: "Amérique du Sud" },
    { nationality: "Bosniaque", continent: "Europe" },
    { nationality: "Botswanais", continent: "Afrique" },
    { nationality: "Brésilien", continent: "Amérique du Sud" },
    { nationality: "Britannique", continent: "Europe" },
    { nationality: "Brunéien", continent: "Asie" },
    { nationality: "Bulgare", continent: "Europe" },
    { nationality: "Burkinabé", continent: "Afrique" },
    { nationality: "Burundais", continent: "Afrique" },
    { nationality: "Cambodgien", continent: "Asie" },
    { nationality: "Camerounais", continent: "Afrique" },
    { nationality: "Canadien", continent: "Amérique du Nord" },
    { nationality: "Centrafricain", continent: "Afrique" },
    { nationality: "Chilien", continent: "Amérique du Sud" },
    { nationality: "Chinois", continent: "Asie" },
    { nationality: "Colombien", continent: "Amérique du Sud" },
    { nationality: "Congolais", continent: "Afrique" },
    { nationality: "Sud-Coréen", continent: "Asie" },
    { nationality: "Nord-Coréen", continent: "Asie" },
    { nationality: "Cubain", continent: "Amérique du Nord" },
    { nationality: "Danois", continent: "Europe" },
    { nationality: "Djiboutien", continent: "Afrique" },
    { nationality: "Dominicain", continent: "Amérique du Nord" },
    { nationality: "Égyptien", continent: "Afrique" },
    { nationality: "Émirati", continent: "Asie" },
    { nationality: "Espagnol", continent: "Europe" },
    { nationality: "Estonien", continent: "Europe" },
    { nationality: "Éthiopien", continent: "Afrique" },
    { nationality: "Français", continent: "Europe" },
    { nationality: "Gabonais", continent: "Afrique" },
    { nationality: "Grec", continent: "Europe" },
    { nationality: "Guinéen", continent: "Afrique" },
    { nationality: "Haïtien", continent: "Amérique du Nord" },
    { nationality: "Indien", continent: "Asie" },
    { nationality: "Indonésien", continent: "Asie" },
    { nationality: "Irlandais", continent: "Europe" },
    { nationality: "Israélien", continent: "Asie" },
    { nationality: "Italien", continent: "Europe" },
    { nationality: "Japonais", continent: "Asie" },
    { nationality: "Marocain", continent: "Afrique" },
    { nationality: "Mexicain", continent: "Amérique du Nord" },
    { nationality: "Néerlandais", continent: "Europe" },
    { nationality: "Néo-Zélandais", continent: "Océanie" },
    { nationality: "Nigérian", continent: "Afrique" },
    { nationality: "Norvégien", continent: "Europe" },
    { nationality: "Pakistanais", continent: "Asie" },
    { nationality: "Palestinien", continent: "Asie" },
    { nationality: "Péruvien", continent: "Amérique du Sud" },
    { nationality: "Philippin", continent: "Asie" },
    { nationality: "Polonais", continent: "Europe" },
    { nationality: "Portugais", continent: "Europe" },
    { nationality: "Qatari", continent: "Asie" },
    { nationality: "Roumain", continent: "Europe" },
    { nationality: "Russe", continent: "Europe/Asie" },
    { nationality: "Sénégalais", continent: "Afrique" },
    { nationality: "Serbe", continent: "Europe" },
    { nationality: "Suisse", continent: "Europe" },
    { nationality: "Turc", continent: "Asie/Europe" },
    { nationality: "Ukrainien", continent: "Europe" },
    { nationality: "Vietnamien", continent: "Asie" },
    { nationality: "Zambien", continent: "Afrique" },
    { nationality: "Zimbabwéen", continent: "Afrique" }
];
