export const nationalities = [
    "Afghan", "Sud-Africain", "Albanais", "Algérien", "Allemand", "Américain",
    "Andorran", "Angolais", "Antiguayen", "Saoudien", "Argentin", "Arménien",
    "Australien", "Autrichien", "Azerbaïdjanais", "Bahaméen", "Bahreïni",
    "Bangladais", "Barbadien", "Belge", "Bélizien", "Béninois", "Bhoutanais",
    "Biélorusse", "Birman", "Bolivien", "Bosniaque", "Botswanais", "Brésilien",
    "Britannique", "Brunéien", "Bulgare", "Burkinabé", "Burundais", "Cap-Verdien",
    "Cambodgien", "Camerounais", "Canadien", "Centrafricain", "Chilien", "Chinois",
    "Chypriote", "Colombien", "Comorien", "Congolais", "Sud-Coréen", "Nord-Coréen",
    "Costaricien", "Ivoirien", "Croate", "Cubain", "Danois", "Djiboutien",
    "Dominicain", "Dominiquais", "Égyptien", "Émirati", "Équatorien", "Érythréen",
    "Espagnol", "Estonien", "Eswatini", "Éthiopien", "Fidjien", "Finlandais",
    "Français", "Gabonais", "Gambien", "Géorgien", "Ghanéen", "Grec", "Grenadien",
    "Guatémaltèque", "Guinéen", "Guinéen-Bissau", "Guyanais", "Haïtien",
    "Hondurien", "Hongrois", "Indien", "Indonésien", "Irakien", "Iranien", "Irlandais",
    "Islandais", "Israélien", "Italien", "Jamaïcain", "Japonais", "Jordanien",
    "Kazakh", "Kényan", "Kirghiz", "Kiribatien", "Koweïtien", "Laotien", "Letton",
    "Libanais", "Libérien", "Libyen", "Liechtensteinois", "Lituanien", "Luxembourgeois",
    "Macédonien", "Malaisien", "Malawien", "Maldivien", "Malien", "Maltais",
    "Marocain", "Mauricien", "Mauritanien", "Mexicain", "Micronésien", "Moldave",
    "Monégasque", "Mongol", "Monténégrin", "Mozambicain", "Namibien", "Nauruan",
    "Néerlandais", "Néo-Zélandais", "Népalais", "Nicaraguayen", "Nigérien",
    "Nigérian", "Norvégien", "Omanien", "Ougandais", "Ouzbek", "Pakistanais",
    "Palaosien", "Palestinien", "Panaméen", "Papouan", "Paraguayen", "Péruvien",
    "Philippin", "Polonais", "Portoricain", "Portugais", "Qatari", "Roumain",
    "Russe", "Rwandais", "Saint-Lucien", "Salomonais", "Salvadorien", "Samoan",
    "Sénégalais", "Serbe", "Seychellois", "Sierra-Léonais", "Singapourien",
    "Slovaque", "Slovène", "Somalien", "Soudanais", "Sri-Lankais", "Sud-Soudanais",
    "Suédois", "Suisse", "Surinamais", "Syrien", "Tadjik", "Tanzanien", "Tchadien",
    "Tchèque", "Thaïlandais", "Togolais", "Tongien", "Tunisien", "Turc",
    "Turkmène", "Tuvaluan", "Ukrainien", "Uruguayen", "Vanuatuan", "Vénézuélien",
    "Vietnamien", "Yéménite", "Zambien", "Zimbabwéen"
  ]
  